<?php
include_once "SuperTruck.php";

class OptimusTruck extends SuperTruck
{
    private function optimusMessage()
    {
        echo "OPTIMUS: I'm Optimus Prime! You shall not past!!!" . PHP_EOL;
    }

    public function __construct(int $maxSpeed)
    {
        parent::__construct($maxSpeed);
        $this->optimusMessage();
    }

    public function stop()
    {
        parent::stop(); // TODO: Change the autogenerated stub
        echo "OPTIMUS: stop" . PHP_EOL;
    }


}